### ISSUE TITLE
Add --output option for easier file output  

### ISSUE THREAD

**Issue by lexxyungcarter** [mtrajano/laravel-swagger#19]
Thank you for such a wonderful package. It's been a life-saver!

I would like to suggest the addition of `--output="/path/file.json"` option. It would greatly assist in creating a custom command to trigger the auto-generation. Currently, calling 
`php artisan laravel-swagger:generate > storage/api-docs/api-docs.json --filter="/api"` inside another command generates an error (either due to the `>`), hence, the `--output` option would really come in handy.

**Comment by mtrajano** [comment]
This is should be easy enough to implement, can get something out by tonight but feel free to submit a or if you get around to it before me, thanks

**Comment by mtrajano** [comment]
Added an option for this in master so you should be able to use it if you version the package to `dev-master` will cut a new release once I add the UI feature as well.
