### ISSUE TITLE
Generate params from Requests

### ISSUE THREAD

**Issue by pleaz** [mtrajano/laravel-swagger#27]
- Laravel Swagger Version: master
- Laravel Version: 6
- PHP Version: 7.4

### Description:

seems like generator doesn't parse Requests,
I called controller and request class like in your sample, but haven't got params in JSON file
Does somebody test it ?
also will you implement generation samples of response using laravel resource classes?

**Comment by mtrajano** [comment]
Released fix in v0.6.2, thanks for the pr
