### ISSUE TITLE
Laravel 7 support

### ISSUE THREAD

**Issue by nenads** [mtrajano/laravel-swagger#43]
- Laravel Swagger Version: 0.6.3
- Laravel Version: 7.6.2
- PHP Version: 7.3.14

### Description:

composer require mtrajano/laravel-swagger

Problem 1
    - Conclusion: remove phpdocumentor/reflection-common 2.0.0
    - Conclusion: don't install phpdocumentor/reflection-common 2.0.0
    - phpdocumentor/reflection-docblock 4.3.0 requires phpdocumentor/reflection-common ^1.0.0 -> satisfiable by phpdocumentor/reflection-common[1.0, 1.0.1].
    - phpdocumentor/reflection-docblock 4.3.1 requires phpdocumentor/reflection-common ^1.0.0 -> satisfiable by phpdocumentor/reflection-common[1.0, 1.0.1].
    - Can only install one of: phpdocumentor/reflection-common[1.0, 2.0.0].
    - Can only install one of: phpdocumentor/reflection-common[1.0.1, 2.0.0].
    - Installation request for phpdocumentor/reflection-common (locked at 2.0.0) -> satisfiable by phpdocumentor/reflection-common[2.0.0].
    - Installation request for mtrajano/laravel-swagger ^0.6.3 -> satisfiable by mtrajano/laravel-swagger[v0.6.3].
    - Conclusion: don't install phpdocumentor/reflection-docblock 5.1.0|install phpdocumentor/reflection-docblock 4.3.0|install phpdocumentor/reflection-docblock 4.3.1
    - Conclusion: remove phpdocumentor/reflection-docblock 5.1.0|install phpdocumentor/reflection-docblock 4.3.0|install phpdocumentor/reflection-docblock 4.3.1
    - mtrajano/laravel-swagger v0.6.3 requires phpdocumentor/reflection-docblock ^4.3 -> satisfiable by phpdocumentor/reflection-docblock[4.3.0, 4.3.1, 4.3.2, 4.3.3, 4.3.4].
    - Can only install one of: phpdocumentor/reflection-docblock[4.3.2, 5.1.0].
    - Can only install one of: phpdocumentor/reflection-docblock[4.3.3, 5.1.0].
    - Can only install one of: phpdocumentor/reflection-docblock[4.3.4, 5.1.0].
    - Installation request for phpdocumentor/reflection-docblock (locked at 5.1.0) -> satisfiable by phpdocumentor/reflection-docblock[5.1.0].

**Comment by mtrajano** [comment]
Hey I will look into this tonight, you're the 2nd person to report this. Looks like laravel 7 or some package it's using requires version 5 of `phpdocumentor/reflection-docblock` and we're still on 4.3. I aready upgraded on the 7.x branch that I'm cleaning up and there were no breaking changes.

**Comment by nenads** [comment]
Grate news !!!

Thanks !!!

**Comment by zFly** [comment]
@mtrajano This bug also affects

* Laravel Version: 6.18.7 
* PHP Version is 7.4.4

I tried `composer require mtrajano/laravel-swagger:0.7.x-dev` but I got the same error. (because you mentioned the 7.x branch)

Just wanted you to know this. Keep up the great work!! :)

**Comment by mtrajano** [comment]
@zFly I had not pushed my changes yet. I just updated the v0.7 branch would you or @nenads be able to try again? Sorry about that

**Comment by mtrajano** [comment]
I probably won't push this to the the v0.6.x branch since it breaks compatibility, can you please try upgrating to `0.7.x-dev` @nenads? There are a lot of extra exciting features coming 😄

**Comment by zFly** [comment]
Using `composer require mtrajano/laravel-swagger:0.7.x-dev` worked for me. 

Thank you for the quick response :)

**Comment by nenads** [comment]
Same !!!! 👍 

Using composer require mtrajano/laravel-swagger:0.7.x-dev worked for me.

Thank you for the quick response :)

**Comment by mtrajano** [comment]
Great!

**Comment by zeke8402** [comment]
When I tried requiring mtrajano/laravel-swagger:0.7.x-dev, I receive this error. 
<img width="1483" alt="Screen Shot 2020-07-17 at 00 47 30 AM" src="https://user-images.githubusercontent.com/1671173/87753548-75163e00-c7c8-11ea-880a-c1fbbc142586.png">

**Comment by zeke8402** [comment]
I get this when trying to install the 0.7.x-dev branch using PHP 7.3 and PHP 7.4, fresh Laravel install.
<img width="1483" alt="Screen Shot 2020-07-17 at 00 47 30 AM" src="https://user-images.githubusercontent.com/1671173/87753702-cfaf9a00-c7c8-11ea-93cc-ff339fdedd21.png">

**Comment by tim-rosseel** [comment]
Same as https://github.com/mtrajano/laravel-swagger/issues/52? 

I tried composer require mtrajano/laravel-swagger:0.7.x-dev, but that asked  for a token that I don't know...
