### ISSUE TITLE
The "--filter" option does not exist.

### ISSUE THREAD

**Issue by Reasno** [mtrajano/laravel-swagger#5]
When I tried the filter option the console said it didn't exist, though it was in the readme. This tool is great by the way.

**Comment by Reasno** [comment]
Oops I just realized the master branch had not been released to packagist. Sorry.

**Comment by raftalks** [comment]
not sure if you did make a new release fixing this, as I have tried to use filter and it is still not available. Btw this is awesome package

**Comment by mtrajano** [comment]
Hey @raftalks sorry that was my fault, I didn't cut a new release when that feature was added. Upgrading the package now should fix this. Feel free to add a new issue if you're still facing the same problem. Thanks!
